### ISSUE TITLE
error in POP3 module

### ISSUE THREAD

**Issue by jstucke** [qeeqbox/honeypots#32]
I received an error when trying to use the included POP3 honeypot module when trying to run the commands from `test_server()`:

```python
Unhandled Error
Traceback (most recent call last):
  File "/lib/python3.10/site-packages/twisted/internet/tcp.py", line 252, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/lib/python3.10/site-packages/twisted/protocols/basic.py", line 439, in dataReceived
    self.lineReceived(line)
  File "/home/jstucke/git/medpot/honeypots/honeypots/pop3_server.py", line 158, in lineReceived
    POP3.lineReceived(self, line)
  File "/lib/python3.10/site-packages/twisted/mail/pop3.py", line 525, in lineReceived
    getattr(self, "state_" + self.state)(line)
--- <exception caught here> ---
  File "/lib/python3.10/site-packages/twisted/mail/pop3.py", line 554, in state_COMMAND
    return self.processCommand(*line.split(b" "))
  File "/home/jstucke/git/medpot/honeypots/honeypots/pop3_server.py", line 119, in processCommand
    f = getattr(self, "do_" + command, None)
builtins.TypeError: can only concatenate str (not "bytes") to str

Unhandled Error
Traceback (most recent call last):
  File "/lib/python3.10/site-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/lib/python3.10/site-packages/twisted/python/log.py", line 85, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/lib/python3.10/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/lib/python3.10/site-packages/twisted/python/context.py", line 83, in callWithContext
    return func(*args, **kw)
--- <exception caught here> ---
  File "/lib/python3.10/site-packages/twisted/internet/posixbase.py", line 686, in _doReadOrWrite
    why = selectable.doRead()
  File "/lib/python3.10/site-packages/twisted/internet/tcp.py", line 247, in doRead
    return self._dataReceived(data)
  File "/lib/python3.10/site-packages/twisted/internet/tcp.py", line 252, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/lib/python3.10/site-packages/twisted/protocols/basic.py", line 439, in dataReceived
    self.lineReceived(line)
  File "/home/jstucke/git/medpot/honeypots/honeypots/pop3_server.py", line 158, in lineReceived
    POP3.lineReceived(self, line)
  File "/lib/python3.10/site-packages/twisted/mail/pop3.py", line 525, in lineReceived
    getattr(self, "state_" + self.state)(line)
  File "/lib/python3.10/site-packages/twisted/mail/pop3.py", line 562, in state_COMMAND
    b"".join(e.args),
builtins.TypeError: sequence item 0: expected a bytes-like object, str found
```

The reason seems to be in `honeypots/pop3_server.py:79` where a string is concatenated with a byte string: `"do_" + command`

What is more, the `POP3Error` exceptions used in lines 78 and 82 do not seem to exist anywhere (missing import?).

On a side note: Debugging this was hampered by the fact that disabling all output of the twisted webserver obscures all errors (I had to comment out line 45 `disable_logger(1, tlog)` to see the error -- otherwise there was no output whatsoever that something was wrong. Maybe it would make sense to not disable logging when the `--verbose` option is set?

**Comment by giga-a** [comment]
> On a side note: Debugging this was hampered by the fact that disabling all output of the twisted webserver obscures all errors (I had to comment out line 45 disable_logger(1, tlog) to see the error -- otherwise there was no output whatsoever that something was wrong. Maybe it would make sense to not disable logging when the --verbose option is set?

I will fix the verbose flag
