### ISSUE TITLE
No output being produced

### ISSUE THREAD

**Issue by antoniolm23** [qeeqbox/honeypots#74]
I had installed honeypots from pip3 in python virtual env on Ubunut Server 24.04. 

Whenever I run the command:

`./venv/bin/python3 -m honeypots --setup all`

nothing happens, simply a new prompt is being issued. 
Tried to have a verbose output, but there seems to be nothing wrong. 
How can I solve?

**Comment by sysfu** [comment]
Reproduced this problem on a fresh install within ubuntu 24.04 LTS VM.

**Comment by giga-a** [comment]
Hi @sysfu and @antoniolm23 - How did you install that honeypot package? Is that v0.66?

**Comment by sysfu** [comment]
> Hi @sysfu and @antoniolm23 - How did you install that honeypot package? Is that v0.66?

Honeypots pip pkg version is 0.65.

Installed it via pip with these commands

```
sudo apt install -y python3-pip libpq-dev python3.12-venv
cd /var/opt/; sudo python3 -m venv honeypots
sudo /var/opt/honeypots/bin/pip3 install honeypots
```

**Comment by giga-a** [comment]
@sysfu I did remove the psycopg2 package in v0.66 - I'm going to push that update to pypi

**Comment by giga-a** [comment]
Done, could you please check the new package 0.66

**Comment by sysfu** [comment]
Package successfully updated and there is the terminal output now of `/var/opt/honeypots/bin/python3 -m honeypots --setup all`

```
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/var/opt/honeypots/lib/python3.12/site-packages/honeypots/__init__.py", line 30, in <module>
    from .sniffer import QSniffer
  File "/var/opt/honeypots/lib/python3.12/site-packages/honeypots/sniffer.py", line 10, in <module>
    from scapy.layers.inet import IP, TCP
  File "/var/opt/honeypots/lib/python3.12/site-packages/scapy/layers/inet.py", line 20, in <module>
    from scapy.utils import checksum, do_graph, incremental_label, \
  File "/var/opt/honeypots/lib/python3.12/site-packages/scapy/utils.py", line 33, in <module>
    from scapy.modules.six.moves import range, input, zip_longest
ModuleNotFoundError: No module named 'scapy.modules.six.moves'
```

Full python3 -v output log attached
[hpsetupverbose.log](https://github.com/user-attachments/files/17120017/hpsetupverbose.log)
